[project]
name = "fraud-detection-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.8.4",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "panda>=0.3.1",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
]
